/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Quick Look
 #	author : miyako
 #	2015/04/28
 #
 # --------------------------------------------------------------------------------*/



// --- Quick Look
void QL_REQUEST_PREVIEW(sLONG_PTR *pResult, PackagePtr pParams);
void QL_Get_file_thumbnail(sLONG_PTR *pResult, PackagePtr pParams);
